### ISSUE TITLE
Using 👌 instead of ✅ for "Everything is awesome!"

### ISSUE THREAD

**Issue by jonathan-buhler** [prettier/pretty-quick#120]
A **_very_** minor request, but I was wondering if you'd consider using the 👌 "all good" emoji rather than the ✅ large check mark.

The check mark doesn't really fit in with the other emojis in the sequence (🔍  🎯  ✍️) while 👌 (or 👍 / ✌️) looks more inline.

Cheers!

**Comment by landonbuttars** [comment]
I personally like the big green button. It's easier to immediately see success or failure because of the bright color.

But I'm not going to die on this hill.

**Comment by JounQin** [comment]
Not planned.
