### ISSUE TITLE
Round brackets pattern not working

### ISSUE THREAD

**Issue by Tom4U** [prettier/pretty-quick#125]
It seems the round brackets pattern doesn't work as expected.

This doesn't work:
`pretty-quick --staged --pattern "**/(apps|libs|tools)/**/*"`

This does:
`pretty-quick --staged --pattern "**/apps/**/*" --pattern "**/libs/**/*" --pattern "**/tools/**/*"`

It seems that somehow round brackets aren't supported in this scenario.

**Comment by jimyhdolores** [comment]
Hello, were you able to solve this problem?

**Comment by JounQin** [comment]
A minimal but runnable online reproduction is required.
