### ISSUE TITLE
Fix Readme for Husky 6.0.0

### ISSUE THREAD

**Issue by bendelonlee** [prettier/pretty-quick#130]
As you can see in the Husky documentation (https://www.npmjs.com/package/husky), you can no longer add hooks via a "husky" section in package.json, only in a .husky directory.

Update readme for new users?

Fixed by PR #131

**Comment by dwiyatci** [comment]
As a first-timer using Husky, glad to know this issue exists already and it just helped big time me figuring out what's wrong with my setup. 😅 Thanks a lot! :-)
