### ISSUE TITLE
pretty-quick will break with prettier v3

### ISSUE THREAD

**Issue by joshwooding** [prettier/pretty-quick#164]
Not an issue right now, but pretty-quick will break with v3 due to the removal of resolveConfig.sync (https://github.com/prettier/prettier/pull/12788).

**Comment by omarkhatibco** [comment]
I can confirm this issue as well

**Comment by meabed** [comment]
Yes it breaks
```
/pretty-quick/dist/isSupportedExtension.js:12
  ..._prettier.resolveConfig.sync(file, {
                             ^

TypeError: _prettier.resolveConfig.sync is not a function
```

**Comment by li-jia-nan** [comment]
mark

**Comment by johnhunter** [comment]
Just experienced this too.

**Comment by emanuelasistensi** [comment]
Same problem

**Comment by johnhunter** [comment]
Dependabot / Renovate bots mean this is going to hit a lot of people now when they rebase and try and commit.

**Comment by steveariss** [comment]
Joining the club. Experiencing same problem

**Comment by jakubwolny** [comment]
We had the same issue - the solution was to switch back to lint-staged, as described in:
https://prettier.io/docs/en/precommit.html

**Comment by steveariss** [comment]
> 

You didn't have the same problem? 

The issue seems to be with Prettier v3.

I tried switching to Lint-staged and it also doesn't seem to be happy with Prettier v3.

My fix for now is to stick with Prettier v2.8.8

**Comment by jakubwolny** [comment]
interesting - after following the https://github.com/okonet/lint-staged#installation-and-setup for lint-staged it seems to be working, I don't have any issues with prettier@3

imho it makes sense because lint-staged makes it possible to run anything: i.e. just "prettier" command, it doesn't rely on any prettier internals (like pretty-quick does)

**Comment by steveariss** [comment]
I'll give it another try. I did give up on troubleshooting pretty quick :P

**Comment by dwiyatci** [comment]
> Seems the library is not maintained?

Maybe it still is? It could be that the author @azz only needs more time and prioritises this? 🤞 🙏 😇

**Comment by mgabeler-lee-6rs** [comment]
Threw together #165 as a first attempt at supporting 3.0. I don't know if those changes are 100%, nor if they will still work with 2.x, but it's a start

**Comment by LukasKlement** [comment]
The last release was more than 1.5 years ago, the lint-staged package is a viable alternative that supports prettier v3 already: https://github.com/okonet/lint-staged

**Comment by ptpaterson** [comment]
> Dependabot / Renovate bots mean this is going to hit a lot of people now when they rebase and try and commit.

Yep, this happened to me.

**Comment by cope** [comment]
Same here :(

```
> pretty-quick --staged --pattern "src/**/*.ts"
🔍  Finding changed files since git revision 83ec8716.
C:\git\projects\server\node_modules\.pnpm\pretty-quick@3.1.3_prettier@3.0.0\node_modules\pretty-quick\dist\isSupportedExtension.js:12
  ..._prettier.resolveConfig.sync(file, {
                             ^
TypeError: _prettier.resolveConfig.sync is not a function
    at C:\git\projects\server\node_modules\.pnpm\pretty-quick@3.1.3_prettier@3.0.0\node_modules\pretty-quick\dist\isSupportedExtension.js:12:30
    at Array.filter (<anonymous>)
    at _default (C:\git\projects\server\node_modules\.pnpm\pretty-quick@3.1.3_prettier@3.0.0\node_modules\pretty-quick\dist\index.js:53:157)
    at Object.<anonymous> (C:\git\projects\server\node_modules\.pnpm\pretty-quick@3.1.3_prettier@3.0.0\node_modules\pretty-quick\bin\pretty-quick.js:17:27)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47
Node.js v20.0.0
 ELIFECYCLE  Command failed with exit code 1.
husky - pre-commit hook exited with code 1 (error)
```

**Comment by MrSwitch** [comment]
Or without _pretty-quick_, replacing the line in Husky(other task runners are available)'s `./.husky/pre-commit` with...

```sh
LIST=`git diff-index --name-only HEAD`; if [ "$LIST" ]; then npx prettier --write $LIST; git add $LIST; fi
```

**Comment by ggualiato** [comment]
> Or without _pretty-quick_, replacing the line in Husky(other task runners are available)'s `./.husky/pre-commit` with...
> 
> ```shell
> LIST=`git diff-index --name-only HEAD`; if [ "$LIST" ]; then npx prettier --write $LIST; git add $LIST; fi
> ```

It doesn't work, this solution adds to the commit all the changed files, and not only the staged ones.

**Comment by MrSwitch** [comment]
> It doesn't work, this solution adds to the commit all the changed files, and not only the staged ones.

Updated with flag `--cached`

**Comment by ggualiato** [comment]
> > It doesn't work, this solution adds to the commit all the changed files, and not only the staged ones.
> 
> Brutal! Updated with flag `--cached`

Now it works better, but if you're using the `--staged` flag from `pretty-quick`, it will not have the same behaviour

**Comment by murtuzaalisurti** [comment]
facing the same issue, moved to lint-staged for this reason

**Comment by bennycode** [comment]
I replaced `pretty-quick` (because it is incompatible with Prettier v3) with [lefthook](https://github.com/evilmartians/lefthook). 

Here is a PR of mine that shows how to migrate to lefthook: https://github.com/bennycode/ts-node-starter/pull/601/files

**Comment by Kordrad** [comment]
I am working on a CLI tool to automatically configure projects. I decided to change **pretty-quick** in favor of **lint-staged**, precisely because **lint-staged** works perfectly without any problems.

If anyone wants to see the configuration files they can be found here:
[.husky/pre-commit](https://github.com/Kordrad/Confiks/blob/2ee08233c06ce5414e708c3f50316d5321a05f97/.husky/pre-commit)
[.lintstagedrc](https://github.com/Kordrad/Confiks/blob/2ee08233c06ce5414e708c3f50316d5321a05f97/.lintstagedrc)
[package.json](https://github.com/Kordrad/Confiks/blob/2ee08233c06ce5414e708c3f50316d5321a05f97/package.json)

**Comment by JounQin** [comment]
See https://github.com/prettier/pretty-quick/pull/165#issuecomment-1891463129

> I'll take over @azz's place and help to maintain this package in few days. 🍻

**Comment by murtuzaalisurti** [comment]
moved to [lint-staged](https://github.com/lint-staged/lint-staged) just because of this issue

**Comment by JounQin** [comment]
I have to reset the related PR #164 because it is full of bugs actually...

I'll rewrite the whole package with TypeScript.

**Comment by JounQin** [comment]
I finished my promise. `pretty-quick` v4 has just been released with `prettier` v3 support! Thanks @SukkaW for helping as always! ❤️

**Comment by taylorkline** [comment]
Should prettier/prettier#15337 be reverted and `pretty-quick` be added back to the docs of pre-commit solutions?
