### ISSUE TITLE
SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by lium115** [prettier/pretty-quick#167]
An error occurred while running the command
 `yarn pretty-quick`

<img width="1596" alt="企业微信20230905-193738@2x" src="https://github.com/azz/pretty-quick/assets/15070438/53fd1849-f663-48f7-9112-6c1bc32ab843">

**Comment by JounQin** [comment]
A minimal but runnable online reproduction is required.

**Comment by JounQin** [comment]
It seems thrown from your prettier plugin and your Node version is outdated.
