### ISSUE TITLE
SyntaxError: '(' expected

### ISSUE THREAD

**Issue by avrim-tr** [prettier/pretty-quick#194]
HI,

I have been using pretty-quick for sometime, today I saw an error, which I do not know why:

I am using Angular and this line:
`private readonly modalRef: MatDialogRef<any> = inject(MatDialogRef<any>)` is causing this error:

`SyntaxError: '(' expected.`

Any ideas?

Versions details:

"pretty-quick": "3.1.3"
"prettier": "2.6.2"
"eslint-config-prettier": "^8.8.0"
node js: 16.14.0
angular: 14.3.0

**Comment by JounQin** [comment]
That's mostly like that your `prettier` version does not recognize the TypeScript syntax, it has nothing related to `pretty-quick`.
