### ISSUE TITLE
Prettier-eslint support

### ISSUE THREAD

**Issue by eramdam** [prettier/pretty-quick#22]
Would it be possible to integrate support [prettier-eslint](https://github.com/prettier/prettier-eslint)? Or at least have some pointers to know what it would take to make a PR to support it 😊

**Comment by azz** [comment]
`prettier-eslint` has a lot of extra configurability that I don't think the minimal API that this module uses can support.  https://github.com/prettier/prettier-eslint#options

I'd be interested to hear a proposal for a way we could make it work with no extra config!

**Comment by eramdam** [comment]
Ideally it would just invoke the `format` method of prettier-eslint with the default options, leaving the configuration up to the user's `.eslintrc` file. From what I can see in the doc of prettier-eslint, by default it will find the proper eslint/prettier configuration files for the given files so I feel like you would not have to pass a lot of options? 

https://github.com/prettier/prettier-eslint#eslintpath-string
https://github.com/prettier/prettier-eslint#prettierpath-string

**Comment by rfgamaral** [comment]
I guess no progress was made on this as of yet?

**Comment by pmcnr-hx** [comment]
Lack of `prettier-eslint` support is currently my blocker for using `pretty-quick`. Just invoking with defaults and handling configuration externally, would be absolutely fine and shouldn't be too disruptive. Would you consider a PR if there were no other externally visible changes to `pretty-quick` aside from an option to use `prettier-eslint` instead of plain `prettier`?

**Comment by shahankit** [comment]
You can achieve similar functionality using just `prettier-eslint` module. I use the following configuration:
```
"lint-staged": {
    "app/**/*.{js,jsx}": [
      "eslint --fix",
      "prettier-eslint --config .prettierrc.json --write",
      "git add"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  }
```

**Comment by smac89** [comment]
I use the following yaml config with `lint-staged` in order to work with `prettier-eslint`:

```yaml
"app/{src,cypress}/**/*.{js,tsx,ts,jsx}":
  - cd app && yarn prettier-eslint '$@' --write --prettier-last
```

In order for the above to work, I use the following command to run `lint-staged`:

```sh
npx lint-staged --shell /bin/sh
```

**Comment by JounQin** [comment]
It will be done in https://github.com/prettier-eslint/prettier-plugin
